
/accelerator/isoCentre 1000 mm      # distance between the isocentre and the target of the accelerator
/accelerator/rotation90Y false      # rotate the accelerator of 90 deg around Y axis
#/accelerator/rotationX 0 deg       # rotation around X [deg]
#/accelerator/rotationX 200 deg     # rotation around X [deg]
#/accelerator/rotationX -45 deg     # rotation around X [deg]

#/accelerator/idEnergy 6             # no units
/accelerator/aperture1X 25 cm           
/accelerator/aperture2X 25 cm      
/accelerator/aperture1Y -100 mm     
/accelerator/aperture2Y 100  mm     

/accelerator/leavesA 25            
/accelerator/leavesA 25
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25 
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25 
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25 
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25            
/accelerator/leavesA 25 
           

/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25                                        
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25  
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25   
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25  
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25            
/accelerator/leavesB 25         
          

